# App model settings
model:
  provider: openai
  name: gpt-4o-mini

# Transcript storage
storage:
  backend: file
  transcripts_dir: sessions
  resume: null

# Runtime behaviour
runtime:
  stream: true

ui:
  config: ui.yaml

